Ftp_Port:21
SftpPort:22
Ftp_Host1:ftp2.adeptia.com

FtpSrc@Location:/Shivam_Singh/Source
SftpSrc@Location:/SFTP/Shivam_Singh/Source

FtpTrgt_Location:/Shivam_Singh/Destination
SftpTrgt_Location:/SFTP/Shivam_Singh/Target

File@Location:/shared/ss
AddOnConfig:jschLoggingLevel=TRACE

Email:shivam.singh@adeptia.com
